package common.user;

// Generated Apr 10, 2017 3:38:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ethnics generated by hbm2java
 */
public class EthnicENT{

	private Integer ethnicID;
	private String ethnic;


	public Integer getEthnicID() {
		return this.ethnicID;
	}

	public void setEthnicID(Integer ethnicID) {
		this.ethnicID = ethnicID;
	}

	public String getEthnic() {
		return this.ethnic;
	}

	public void setEthnic(String ethnic) {
		this.ethnic = ethnic;
	}

}
